name: KatzcraftPets
version: '1.3'
main: de.castmax1311.katzcraftpets.Main
api-version: '1.16'
description: A plugin to interact with your tamed pets
commands:
  givepet:
    description: Transfer your tamed animal to another player
    usage: /givepet <petname> <player>
  ridepet:
    description: Let your pet carry you
    usage: /ridepet
  tame:
    description: Tame an untamed animal near you
    usage: /tame
  untame:
    description: Untame your tamed animal near you
    usage: /untame
  saddle:
    description: Put a saddle on a horse
    usage: /saddle